### ISSUE TITLE
Supprimer fichier contributions du site

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/eig-link#119]
Est-il utile de conserver [cette page](https://doc.eig-forever.org/contributions.html) sur le site ? Elle n'est pas remplie pour l'année 2019 (peut-être qu'on va le faire).

Je pense qu'elle a plus vocation à être archivée qu'autre chose.

Du même avis @jbledevehat ?

**Comment by jbledevehat** [comment]
Hmmm je pense qu'on peut produire un contenu similaire mais simplifié pour 2019. Avec le recul je ne suis pas sur de l'archiver car elle synthétise bien ce qui c'est livré/produit en une page. Finalement je la trouve assez utile... @ en discuter

**Comment by AntoineAugusti** [comment]
J'ai archivé les contributions 2018 dans un commit. Les contributions 2019 sont [dans un tableur](https://docs.google.com/spreadsheets/d/1Xm4P9d_6jQYBYXDsOPJPSrtOb7pt1SYQ3v2H_YoBaKE/edit?usp=sharing)
