### ISSUE TITLE
Compte admin/root Proxmox 

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/eig-link#141]
Je ne suis pas root/admin sur le Proxmox EIG, prévoir de créer un compte admin pour Raphaëlle Roffo.

Je me chargerai de faire un tour de présentation mais il est possible qu'elle te pose des questions ensuite

**Comment by bzg** [comment]
Fait, je prends contact avec Raphaëlle directement pour l'accès.

**Comment by bzg** [comment]
C'est bon pour Raphaëlle. @AntoineAugusti je note de te retirer l'accès d'ici deux mois, si c'est OK pour toi.
