### ISSUE TITLE
Compte DNS eig-forever.org

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/eig-link#142]
Prévoir de créer un compte pour Raphaëlle Roffo afin de gérer les DNS de eig-foreverg.org sur DigitalOcean. Voir pour le transfert au programme EIG et mettre fin à cette responsabilité pour toi.

Supprimer mon compte ensuite 😉

**Comment by bzg** [comment]
Je viens d'envoyer les mails d'invitation aux EIG Link pour la gestion des DNS de eig-forever.org.

**Comment by bzg** [comment]
C'est bon.
