### ISSUE TITLE
Définir qui est en maintenance pour les dépôts EIG hébergés par github.com/entrepreneur-interet-general

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#146]
Il s'agit ici des dépôts écrits par les EIG Link au fil des ans et qui demandent à être maintenus par l'équipe technique d'Etalab... dans les périodes de transition entre deux promotions EIG, où il n'y a pas d'EIG Link.

**Comment by AntoineAugusti** [comment]
Tu as quoi comme dépôts en tête ? Normalement les dépôts sur l'orga etalab sont maintenus par les équipes techniques d'Etalab à la fin de la mission et les dépôts sur l'orga EIG sont maintenus par les EIG Link des promotions suivantes.

Certains dépôts sont orphelins à ton avis ?

**Comment by bzg** [comment]
Je me suis emballé : je voulais simple dire qu'il faut que l'équipe technique d'Etalab soit clairement au courant qu'il y a toujours une période pendant laquelle des dépôts EIG Link sont sans mainteneur, entre deux promotions.  J'ai modifié le sujet... et fermé l'issue, qui n'est pas pertinente.
