### ISSUE TITLE
Développer un outil pour la bulloterie

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#39]
La [bulloterie](http://movilab.org/index.php?title=La_Bulloterie) est un outil pour partager ses compétences.

Il a été testé avec les EIG lors du premier bootcamp et avec les mentors lors d'une session mentor.

Les données issues de la bulloterie EIG ont été notées à la main et une première mise en forme en a été faite par @phileas-condemine - mais il n'y a pas eu d'autre outil autour depuis.

Trois outils peuvent être imaginés:

- [ ] un outil de collecte des données
- [ ] un outil de présentation des données collectées
- [ ] un outil permettant de faire les deux pendant une bulloterie

**Comment by phileas-condemine** [comment]
Il faut que je prenne un full mercredi pr bosser sur une app de saisie en
shiny connectée avec la google sheet actuelle + connecter l'app de
resistution a la google sheet

**Comment by JulienParis** [comment]
ya pe moyen de récupérer le code mon site-portfolio et de l'adapter : [http://jpylab.fr/](http://jpylab.fr/)
Le code est un peu vieux et pas encore en opensource, mais il y a une interface pour ajouter des nodes à la volée... 
sinon dans la même veine "mes vieux projets" il y a aussi [LibViz](http://libviz.artlabo.org/), basé sur des collections Zotero... code ici : [https://github.com/JulienParis/LibViz](https://github.com/JulienParis/LibViz)

**Comment by AntoineAugusti** [comment]
Je ne suis pas au courant d'un avancement notable sur cette question et le besoin n'était pas bloquant. Je ferme.
