### ISSUE TITLE
Proposer de faire les sessions sur une journée par mois

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#40]
Avoir 3h30 de session d'accompagnement de 15h à 18h30 tous les quinze jours ne paraît pas correspondre au format idéal.

Cela laisse trop peu de temps pour des échanges informels, trop de temps est pris pour l'accueil, la pause, les discussions de couloir, et c'est contraignant pour ceux qui viennent de loin.

Une idée serait de plutôt faire une journée entière par mois, avec des temps de "production" bien délimités.

**Comment by AntoineAugusti** [comment]
1 fois / par mois me parait peu pour garder un contact physiquement entre les différents défis.

Que pensez-vous d'une fois par mois pour les ateliers et d'une fois toutes les 2 semaines pour des discussions informelles autour d'un verre en fin de journée ?

**Comment by AntoineAugusti** [comment]
Le programme d'accompagnement prévoit des séances d'une journée dorénavant, pour les mentors et les EIG.

Voir la page dédiée à l'accompagnement https://github.com/entrepreneur-interet-general/eig-link/blob/master/accompagnement.md
