### ISSUE TITLE
Passer de Slack à Mattermost

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#41]
Les EIG 2 ont utilisé Slack comme outil pour communiquer au quotidien.

Les fonctionnalités sont pertinentes et l'outil est très utilisé pour les échanges entre EIG, c'est un outil clef pour la construction du collectif et l'encouragement d'échanges informels.

Dans l'idée d'encourager l'utilisation de solutions libres, Etalab pourrait encourager le passage à Mattermost - comme ce qui a été fait pour les mentors EIG.

**Comment by AntoineAugusti** [comment]
Pour le moment on conserve Slack car :
- il y a déjà plusieurs promos d'EIG dessus
- les mentors EIG 3 ont leur Slack également
- Etalab et Beta Gouv utilisent également Slack
