### ISSUE TITLE
Trouver une façon de reprendre les agendas Nextcloud

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#42]
Pour EIG 2, je maintenais deux agendas, l'[agenda EIG](https://github.com/entrepreneur-interet-general/agenda-eig2018) et l'[open agenda EIG](https://github.com/entrepreneur-interet-general/open-agenda-eig2018).

Les événements sont ajoutés dans les dépôts github puis synchronisés depuis un ordinateur perso vers les agenda Nextcloud.

Il faudrait trouver une façon de faire pour continuer de permettre à plusieurs EIG de proposer des événements et qu'ils soient lisibles via https://cloud.eig-forever.org ou une autre instance Nextcloud.

**Comment by AntoineAugusti** [comment]
Peut-on imaginer créer un évènement sur son calendrier, inviter une adresse mail magique d'EIG forever et voir l'événement apparaitre là-bas ?

**Comment by AntoineAugusti** [comment]
On s'oriente vers 2 agendas : un privé pour la promo EIG + un public pour les événements EIG ouverts.

À voir comment intégrer les événements que proposent les EIG sur les calendriers. Peut-être par Slack ? E-mail ?
