### ISSUE TITLE
Sanctuariser les mercredi après-midi pour de l'inter-EIG

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#43]
Pour EIG 2, les EIG ont eu à leur diposition une salle au LLL tous les mercredi après-midi, et plusieurs d'entre eux ont pris l'habitude de s'y retrouver.

Les mercredi après-midi ont aussi servi à la permanence mise en place par Quentin (le référent technique du LLL).

Pour EIG 3, il peut être envisagé de proposer un tel créneau hebdomadaire dès le début du programme, voire de thématiser les interactions EIG pendant ces moments: par exemple pour y faire des sessions de [design/code/model review](https://github.com/entrepreneur-interet-general/eig-link/issues/55).

**Comment by AntoineAugusti** [comment]
Part entière du programme d'accompagnement maintenant #86
