### ISSUE TITLE
Valoriser la page outils.org

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#45]
La page [outils.org](https://github.com/entrepreneur-interet-general/eig-link/blob/master/outils.org) contient une liste d'outils mentionnés par les EIG sur slack ou ailleurs.

Elle est faite pour donner des idées de ce qui peut être utilisé, ce n'est pas une liste de recommandations.

Des idées pour rendre cette liste plus utile:

- [ ] demander aux EIG de la compléter
- [ ] y ajouter des commentaires
- [ ] y ajouter un système de "+1" pour faire remonter les outils populaires
- [ ] y associer des EIG comme "référents" qui peuvent être mobilisés

Toute autre idée est la bienvenue!

**Comment by AntoineAugusti** [comment]
On a pas vraiment continué cette initiative lors de la promotion 3 malheureusement.
