### ISSUE TITLE
Utiliser un outil dédié pour les listes de discussion

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#46]
Aujourd'hui, Etalab passe par le service https://framalistes.org pour les listes de discussion (`eig2018@`, `eig2018-mentors@`, etc.)

Nous pourrions utiliser un nouveau nom de domaine (`eig-tools.org`) pour y installer une instance de [yunohost](https://yunohost.org/) et déployer un service de listes de discussions avec [mailman](http://www.list.org/) ou [sympa](https://www.sympa.org/).

**Comment by AntoineAugusti** [comment]
Pourquoi vouloir changer @bzg ?

**Comment by AntoineAugusti** [comment]
Pour l'année 2019 nous sommes sur [Framalistes](https://framalistes.org) pour le moment, par souci de simplicité et pour promouvoir l'action de Framasoft. À voir si on évolue à terme, mais ce n'est pas prévu pour les mois à venir

**Comment by bzg** [comment]
Je ne suis pas sûr qu'il faille promouvoir l'action de Framasoft. Et Framasoft rappelle souvent son objectif, qui est d'encourager les autres à utiliser leurs propres outils de "dégooglisation". Mais bien sûr, c'est ok pour l'instant (et c'est un problème qui n'est pas spécifique à EIG).

Mon outil préféré pour les listes de discussion est [Mailman](https://fr.wikipedia.org/wiki/GNU_Mailman) qu'on peut déployer facilement à partir de [yunohost](https://yunohost.org/).
