### ISSUE TITLE
Trouver une meilleure formule pour le suivi hebdomadaire

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#47]
Pour EIG 2, nous avons mis en place un rituel de suivi hebdomadaire.

Nous avons commencé par des comptes-rendus sur slack tous les vendredi à 11h30, puis l'envoi de mails sur la liste le vendredi, puis nous sommes revenus à un "stand-up" le vendredi.

Les retours envoyés par mail sur la liste `eig2018` étaient ensuite publiés sur le fichier [suivi.org](https://github.com/entrepreneur-interet-general/eig-link/blob/master/suivi.org).

Il y a plusieurs problèmes:

- il est difficile de s'assurer que tout le monde est disponible sur un même créneau
- l'envoi des mails est utile, mais on tombe vite dans des listes de micro-tâches
- le fichier `suivi.org` est devenu un espace d'archivage plutôt que de suivi
- les tâches étaient aléatoirement associées à des livrables

Quelques pistes pour la suite:

- Maintenir la cadence hebdomadaire qui paraît bonne 
- trouver un outil permettant de partager plus facilement les retours
- s'assurer que chacun est le plus synthétique possible
- s'assurer de faire une place à part aux bonnes et mauvaises nouvelles
- peut-être structurer les retours autour des livrables, s'ils existent

Toute idée est ici la bienvenue.

**Comment by AntoineAugusti** [comment]
Pour cette année, on se tourne vers un suivi qui est effectuée en mode "pull" par l'équipe EIG Link + Node. On se répartit les différents défis et on appelle environ 30 minutes les projets tous les 10-15 jours. Durant cet appel, on pose des questions et on prend un compte-rendu. Ce compte-rendu est archivé dans Trello, par défi. Les informations importantes sont données immédiatement au reste de l'équipe.

On perd la visibilité pour tous du suivi de chaque défi, qui selon nous n'était pas si bénéfique que ça l'année précédente (tous les défis n'avancent pas à la même vitesse, parfois on stagne pendant des semaines et on peut être tenté de dresser un tableau plus beau que la réalité car on est *observé* par d'autres). Pour maintenir quand même cet aspect, chaque défi EIG fera un court compte-rendu d'une minute lors des séances plénières sur une journée à l'aide de [l'outil de standup](https://standup.eig-apps.org).
