### ISSUE TITLE
Stabiliser la gazette EIG

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#48]
La "gazette EIG" est une sorte de mini-newsletter envoyée sur `eig2018` pour indiquer aux EIG ce qui les attend cette semaine.

Elle contient les événements EIG de la semaine, les événements de l'écosystème (Etalab talks, etc.), les relances pour des tâches à faire pour EIG (en plus des tâches pour les défis), les déjeuner de médiation avec chaque défi, etc.

Elle s'avère très utile pour plusieurs EIG.

**Comment by AntoineAugusti** [comment]
Des nouvelles de la Gazette : elle est toujours envoyée tous les lundis. Un rappel est mis en place sur Slack à 16h pour rappeler qu'il faut en envoyer une. On prévoit de répartir la rédaction entre EIG Link et EIG Node

**Comment by bzg** [comment]
Je l'ai trouvé super la dernière gazette !
