### ISSUE TITLE
Amorcer tôt la médiation défi par défi

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#49]
Pour EIG 2, nous avons mis en place des déjeuners par défi à partir du mois de juin.

Ces déjeuners permettent à un membre de l'équipe EIG Node de se mettre à l'écoute des EIG pour savoir ce qui va et ne va pas pour eux.

Ils se sont avérés utiles pour faire remonter des informations qui seraient autrement passées inaperçues.

Pour EIG 3, certainement à refaire en commençant plus tôt ?

**Comment by AntoineAugusti** [comment]
On a fait ça dès le début de la promo 3 avec des référents dans l'équipe core par défi.
