### ISSUE TITLE
Formaliser les contacts avec l'écosystème hors Etalab

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#51]
La semaine de bootcamp a permis de rencontrer d'autres acteurs qu'Etalab: le [LINC](de
) de la CNIL, beta.gouv, etc.

Il était ensuite difficile, pour les EIG et pour les mentors, de quelle façon ils pouvaient mobiliser (ou non) ces acteurs dans le cadre d'EIG.

Pour EIG 3, il peut être intéressant d'imaginer que la première rencontre est suivie d'une deuxième à mi-parcours - les questions seront plus précises, et les acteurs extérieurs pourront aussi se faire une meilleure idée du contenu des défis.

**Comment by AntoineAugusti** [comment]
Il serait bien aussi que chaque interlocuteur donne une adresse mail sur laquelle ils peuvent recevoir des demandes des EIG, sans passer par le site de l'administration et un formulaire de contact

**Comment by AntoineAugusti** [comment]
C'est formalisé dans une page de documentation avec des explications et des points de contact https://doc.eig-forever.org/ecosysteme.html
