### ISSUE TITLE
Proposer un kit d'accueil EIG

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#52]
Un kit d'accueil complet donné lors du premier bootcamp:

- goodies (mug, clef 4G, etc.)
- organigrammes des administrations
- portfolio de projets faits les années précédentes
- biographies des EIG 1 et 2 (et que sont-ils devenus ?)
- la stack des défis précédents
- les outils partagés entre défis des années précédentes
- les moyens de communiquer
- le rituel de suivi hebdomadaire

Toute autre idée est la bienvenue.

**Comment by JulienParis** [comment]
pas forcément dans le kit mais au moment du bootcamp faire la rétrospective photo de comment s'est passée l'année précédente, histoire de donner le ton (les petites vidéos accélérées de Tiphaine + qqs photos EIG hors les murs ou we bateau...)

**Comment by JulienParis** [comment]
- une liste / fiches des structures "sympathisantes" gravitant autour d'Etalab : Bricodeurs ,codeurs en liberté, La Zone, APIdev, Asso alumni EIG...

**Comment by AntoineAugusti** [comment]
Fait par @guenolec et @milkosofi
