### ISSUE TITLE
Encourager le partage de résolution de problèmes

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#54]
La [bulloterie](https://github.com/entrepreneur-interet-general/eig-link/issues/39) a donné envie aux EIG d'apprendre les uns des autres, mais en pratique, cela s'est trop peu fait. Quelques démos et sessions "vis ma vie" ont aussi été proposées, mais au fil de l'eau.

Les [temps inter-EIG](https://github.com/entrepreneur-interet-general/eig-link/issues/43) pourraient être fléchés vers du partage de problèmes résolus ou à résoudre ou des sessions de [design/model/code review](https://github.com/entrepreneur-interet-general/eig-link/issues/55).

**Comment by AntoineAugusti** [comment]
Il y a aussi plusieurs channels qui commencent par `#help-`. Bien relayer leur existence et ne pas hésiter à inviter des gens

**Comment by AntoineAugusti** [comment]
Channel d'aide `help` et sur Bulletins on a un champ dédié aux demandes d'aide de manière hebdomadaire
