### ISSUE TITLE
Structurer l'accompagnement design review / code review / model review

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#55]
Les EIG ont spontanément proposé d'organiser une après-midi de _design review_ et une autre de _model review_.

Les deux se sont avérées utiles et pourraient être encouragées dès le début du programme, soit pendant les temps [inter-EIG](https://github.com/entrepreneur-interet-general/eig-link/issues/43) soit pendant les [journées entières](https://github.com/entrepreneur-interet-general/eig-link/issues/40) du programme d'accompagnement.

**Comment by AntoineAugusti** [comment]
Ces événements ont continué lors de la promo 3. L'équipe Core amène l'initiative et certains EIG se sont proposés d'organiser de tels événements.
