### ISSUE TITLE
Améliorer la communication sur le recrutement

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#56]
Les EIG 1 et 2 se sont mobilisés pour diffuser la campagne de recrutement dans leurs réseaux.

Quelques pistes d'amélioration:

- s'y prendre plus tôt auprès des EIG en expliquant bien les enjeux
- préparer la communication de façon coordonnée
- mieux préparer la session où des proches des EIG sont invités à découvrir EIG n+1
- demander à chaque EIG d'aller chercher X candidat

Toute idée est la bienvenue!

**Comment by AntoineAugusti** [comment]
C'est un sujet entier qui a été abordé durant le dernier séminaire Core et bien pris en compte pour la promo 4.
