### ISSUE TITLE
Définir le quand et le quoi de ce qui est envoyé en amont des sessions d'accompagnement

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#58]
Les EIG reçoivent beaucoup d'emails relatifs au programme.

Parmi ces emails, certains sont quasi systématiques, et concernent les sessions d'accompagnement.

Pour que ces emails se démarquent plus systématiquement du flux d'emails EIG, quelques idées:

- qu'ils soient systématiquement envoyés X jours avant la session
- que leur mise en forme soit la même chaque fois
- qu'ils contiennent les livrables qui seront utilisés lors de la session (ex. matrice)

Les autres idées sont bienvenues!

**Comment by AntoineAugusti** [comment]
Ou adopter une convention de nommage pour les sujets `[Accompagnement] Session du X octobre 2018`

**Comment by AntoineAugusti** [comment]
Je pense que ceci s'est amélioré lors de la promo 3, que ce soit dans les e-mails ou dans le programme maintenu en ligne
