### ISSUE TITLE
Prévoir un accompagnement très en amont concernant la pérennisation des défis

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/eig-link#61]
La thématique "pérennisation des défis" pourrait être prévue dans le programme d'accompagnement plus en amont (à vue de nez à partir de +5 mois pour les EIG, dès le départ pour les mentors), et pourrait se faire sous différentes formes : 

- [ ] retours d'expériences des EIG 1 et 2 : pourquoi les EIG précédents ont cherché à rester en poste, comment chacun a réussi à embrayer ou non sur un contrat (CDD court, long, vacations...), comment négocier ses exigences salariales, circulaires, directives, réglementation contrats dans la fonction publique, etc... 
- [ ] faire de la veille / formaliser une veille sur les vacations / opportunités existantes (pe dans un chan slack dédié)
- [ ] sensibiliser en amont les mentors à la nécessité de prolonger les postes, de ne pas sous-estimer le besoin / aux difficultés de prolonger / aux solutions-hacks possibles
- [ ] présentation + formelle des structures type Bricodeurs / Codeurs en Liberté / collectif ex-EIG ... pour montrer 
- [ ] sensibilisation des mentors aux possibilités de financements alternatives / leur rôle de bizdev : via des associations, fondations, (ex. Carrefour des Innovations Sociales).

**Comment by bzg** [comment]
Oui, il y a un gros travail à faire ici: clarification des besoins et des actions possibles, sachant qu'on est beaucoup dans le « cousu main » au niveau des solutions expérimentées jusque-là. Quelques idées:

- [ ] Améliorer le format de la session d'accompagnement consacrée à la pérennisation
- [ ] Répertorier les scénarios de pérennisation expérimentés pour EIG 1 et 2
- [ ] Faire un « guide de pérennisation » (interne ou public)

J'ai ajouté une section sur la pérennisation dans le mini-guide adressé aux mentors, voir [ce commit](https://github.com/entrepreneur-interet-general/eig-link/commit/e26ad85bad1c44f4acea741013be6cf8f9f8d424).

**Comment by AntoineAugusti** [comment]
On a fait ce travail bien mieux lors de la promo 3 avec de l'accompagnement dès juin, des modèles de note, des sessions à destination des mentors et des EIG
