### ISSUE TITLE
Avoir 2 moments EIG hors les murs prévus au lieu d'un seul

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/eig-link#62]
On pourrait penser deux EIG hors les murs, pe : 
- un premier EIG hors les murs avant les vacances d'été avec les EIG + sympathisants
- un deuxième EIG hors les murs vers la fin du contrat EIG avec EIG + mentors + sympathisants

**Comment by AntoineAugusti** [comment]
C'est le cas pour la promo 2019 !
