### ISSUE TITLE
Rendre les EIG plus visibles aux niveaux de décisions stratégiques de son administration 

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/eig-link#63]
comment préparer des réunions avec les directeurs de services
- défi par défi : un moment de cadrage EIG+mentor+EIG nodes pour parler des particularités  a/ de sa propre administration et de son actualité  b/ de la personnalité et des enjeux propres au directeur de service avec qui sera organisée la réunion ; 
- retours d'expériences EIG 2 et 1 : comment ont été préparées les réunions avec directeurs de services / dir Cab etc ... et quels objectifs ces réunions visaient / victoires - défaites ; 
- pousser les défis / EIG peu visibles au sein de leur administration à avoir au moins 2 ou 3 moments de visibilité auprès de leur plus haut niveau de direction/décision. Objectif : être visible tout le long de l'année auprès de sa direction afin de rentrer dans les esprits /

**Comment by AntoineAugusti** [comment]
Je pense qu'on a fait attention à ceci en promo 3.
