### ISSUE TITLE
Formations courtes mais "obligatoires" des mentors sur les notions/outils de base

### ISSUE THREAD

**Issue by JulienParis** [entrepreneur-interet-general/eig-link#65]
en gros une pédagogie dirigée vers les mentors pour former aux notions de base et acquérir un vocabulaire commun / dans le cadre d'une séance d'accompagnement collective des mentors en début de programme : 

- UI et UX, deux métiers différents
- différences entre métiers dev : admin sys / data scientist / data analyst / devop / dev front ... 
- différences entre : serveur / framework / CSS / load balancer / prod-preprod ...
- qu'est-ce qu'une donnée, un schéma de données, un workflow de données... ? 
- open data : obligations... 
- Slack
- Git
- serveur / application / code / issues / scrum / fork / ... 
- sensibiliser au fait qu'il existe des langages courants mais différents -> donc implications : Python / C# / C++ / R / Java / Javascript / Ruby ...

**Comment by AntoineAugusti** [comment]
Fait dans les premières sessions de mentorat au début de la promo.
