### ISSUE TITLE
Trouver une façon de partager les congés entre EIG

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#68]
Avec plus d'une douzaine d'équipes réparties dans autant d'administrations, il est difficile de savoir à un instant `T` qui est disponible, qui est en congé.

Un calendrier pourrait être partagé à cet effect, par exemple sur le Nextcloud - à condition de s'assurer que tout le monde l'a bien pris en main.

Le calendrier ne serait partagé qu'en interne, sans vocation à être publié.

Voir aussi [cette issue](https://github.com/entrepreneur-interet-general/eig-link/issues/42) sur la façon de reprendre les agendas.

**Comment by AntoineAugusti** [comment]
Que penses-tu de cette issue @jbledevehat ?

**Comment by jbledevehat** [comment]
Cela pourrai être intéressant oui, et à voir si nous ne pourrions pas ajouter d'autres usages, comme les présents les Mercredi aprem ou autres après-midi (afin que tout le monde sache). 
Enfin, je pense que cela doit être une proposition en plénière pour faire l'adhésion de tous, et afin de le valider ou non.

**Comment by AntoineAugusti** [comment]
Pas vraiment bloquand pendant cette promo donc je serai tenté d'abandonner ça. Sauf si @entrepreneur-interet-general/eig-core est contre
