### ISSUE TITLE
Proposer un modèle de signature email (texte et HTML) aux EIG

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#79]
L'idée est de proposer un modèle de signature email en reprenant ce qu'avait fait @jbledevehat l'année dernière.

**Comment by AntoineAugusti** [comment]
Pourquoi pas proposer, mais pas en faveur **d'imposer** un modèle de signature. Peut-être qu'il y a déjà des consignes dans les différents organismes.

Je trouve les signatures complètes avec bandeau, images, adresses postales, fax etc d'un autre temps et très lourdes. Dans une optique de sobriété, je serais plus en faveur d'une signature texte brut, sobre.

*/troll*:
Bonus spécial pour les signatures mentionnant une formule type
> Pour une administration exemplaire, préservons l'environnement. N'imprimons que si nécessaire.

**Comment by bzg** [comment]
Tout à fait d'accord pour ne rien imposer. Ma signature idéale tient en une ligne sous "-- " dans un format texte ;)

**Comment by jbledevehat** [comment]
C'était une proposition, mais après coup, il n'y a pas d'intérêt je trouve.

**Comment by bzg** [comment]
Ok, je ferme, c'était juste pour ne pas perdre l'idée. Merci pour vos retours.
