### ISSUE TITLE
Retirer les références à cloud.eig-forever.org et suivi.eig-forever.org

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#82]
J'ai sauvegardé et effacé l'instance Nextcloud qui tournait sur https://cloud.eig-forever.org, ainsi que la mini-appli qui était sur https://suivi.eig-forever.org

Il faudrait mettre à jour les documents pour supprimer les références.

**Comment by AntoineAugusti** [comment]
C'était déjà fait, merci
