### ISSUE TITLE
Mise en forme de la page contact.md

### ISSUE THREAD

**Issue by bzg** [entrepreneur-interet-general/eig-link#88]
En passant de org-mode à markdown, la page [contacts.md](https://github.com/entrepreneur-interet-general/eig-link/blob/master/contacts.md) s'est cassée.

Je n'ai pas trouvé comment ajouter des liens à l'intérieur de tableaux en markdown, j'aimerais croire que c'est parce que j'ai mal cherché :)

Je signale ce souci de mise en forme à toutes fins utiles.

**Comment by AntoineAugusti** [comment]
Merci @bzg ! En réalité le meilleur moyen pour avoir les informations de contact des EIG est le site web https://entrepreneur-interet-general.etalab.gouv.fr/communaute.html.

En conséquence j'ai supprimé la page.

**Comment by bzg** [comment]
D'ac merci. La page `contact.org` était pratique pour chercher rapidement un nom d'utilisateur sur github ou collecter tous les noms d'utilisateurs Twitter - mais vous avez peut-être un document interne équivalent.

**Comment by AntoineAugusti** [comment]
Oui, c'est le cas. On a une feuille de calcul partagée et on partage des fichiers vCard à toute la promo pour que chacun ait les informations de contact des autres https://github.com/entrepreneur-interet-general/eig-link/issues/66

**Comment by AntoineAugusti** [comment]
On a préféré gardé ça en privé car il y a des informations personnelles (e-mail, téléphone) et il est difficile de maintenir à jour plusieurs choses :
- les infos du site public
- une page Markdown ici
- une feuille de calcul avec les infos publiques + privées
